name: Version

on: push

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: paulhatch/semantic-version@v4.0.2
        with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
        change_path: "src/my-service"
        namespace: my-service
        short_tags: true
        bump_each_commit: false
